### ISSUE TITLE
Dimension Changes Problem (Firefox Android)

### ISSUE THREAD

**Issue by Aang488** [igorlogius/dbl-click-dict#2]
**Describe the bug**
The dimensions of the screen changes, because the definition windows forces it so, when the word is at the end of the line. Here are a few screen shots.

1. Without extension
![image](https://user-images.githubusercontent.com/79444969/234577823-94cf1869-cd1d-4c76-93e2-7b9ea3606cb5.png)

2. With extension but the word is not at the end of line and the definition window does not change the dimensions of the website. (This is perfect)
![image](https://user-images.githubusercontent.com/79444969/234578217-5d9c0c40-b48e-4637-9f37-835c3fc31731.png)

3.  With extension but the word is at the end of line and the definition window changes the dimensions of the website. (This is the bug)-->> I want it to become like Point 2.
![image](https://user-images.githubusercontent.com/79444969/234579848-e9bcd48b-f457-4e1c-b0f9-4e276a4fb4a3.png)

**To Reproduce**
1. Install the extension on firefox nightly or Beta android
2. Double Click on 'Word (at the end of the line)'
3. See error

**Expected behavior**
The dimensions of the website is messed up, the size becomes smaller so long as the definition is displayed.

**Screenshots**
I have added above

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Any Android]
 - OS: [Android 12]
 - Browser [Firefox]
 - Version [113.0b7]

**Additional context**

**Comment by igorlogius** [comment]
That might be a little more involved ... since this will require some calculations that would determine the best position of the bubble and a perfect or even a good position might not even exist. 

A "simple" workaround could be to position the bubble always on the left side when the word is close to the right side or the screen width is small.

**Comment by rehman-talha** [comment]
> That might be a little more involved ... since this will require some calculations that would determine the best position of the bubble and a perfect or even a good position might not even exist. 
> 
> A "simple" workaround could be to position the bubble always on the left side when the word is close to the right side or the screen width is small.  

This seems like the perfect solution. Thanks

**Comment by Aang488** [comment]
Seems like the only work around. Thanks

**Comment by Aang488** [comment]
> That might be a little more_ involved _... since this will require some calculations that would determine the best position of the bubble and a perfect or even a good position might not even exist.
> 
> A "simple" workaround could be to position the bubble always on the left side when the word is close to the right side or the screen width is small.

![image](https://user-images.githubusercontent.com/79444969/234775229-f6e4a037-2f24-456b-9c8f-2bcc5da08601.png)

[Google dictionary](https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja/related) has resolved this problem of dimension.

**Comment by igorlogius** [comment]
> [Google dictionary](https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja/related) has resolved this problem of dimension.

i'll take a look, sadly the source code of that addon is very very obfuscated ... so it's just a bit hard to read and understand it.  But i check if i can find anything useful in it. 
Thanks for the hint.

**Comment by Aang488** [comment]
Absolutely loved it!
