### ISSUE TITLE
A remedy for both issues 
1. Pop up background color
2. Pop up width on Android

### ISSUE THREAD

**Issue by Aang488** [igorlogius/dbl-click-dict#5]
Kindly have a look at it, I generated it via ChatGpt, cuz I know no programing.

https://pastebin.com/5sxnc7xM

**Comment by Aang488** [comment]
> Kindly have a look at it, I generated it via ChatGpt, cuz I know no programing.
> 
> https://pastebin.com/5sxnc7xM
> 
> Also, you removed the addon from Firefox addons store, why?
> 
> 

1. In this code, we first use the window.matchMedia API to check if the user's browser theme is set to dark mode. We then define a style for the definition pop-up that uses the appropriate background color, text color, and border color based on the user's browser theme. We select the existing style element for the definition pop-up by its ID (#mwe-popups-style), replace its text content with the new style (definitionPopupStyle), and apply it to the definition pop-up. This will update the existing style to match the user's browser theme.

Note that this code assumes that the definition pop-up is already present on the page and has an existing style element with the ID mwe-popups-style. You will need to modify this code to suit the specific requirements of your extension.


2. This code defines two styles: one for larger screens with a minimum width of 300 pixels, and one for small screens with a width of 100% (to make sure the pop-up always fits inside the screen). It then adds a media query that targets screens with a maximum width of 480 pixels and adds the small screens style to the existing style element.

**Comment by igorlogius** [comment]
> Also, you removed the addon from Firefox addons store, why?

No i didn't. 

It's here => https://addons.mozilla.org/en-US/firefox/addon/dbl-click-dict/

**Comment by Aang488** [comment]
> > Also, you removed the addon from Firefox addons store, why?
> 
> No i didn't.
> 
> It's here => https://addons.mozilla.org/en-US/firefox/addon/dbl-click-dict/

**Comment by igorlogius** [comment]
> Kindly have a look at it, I generated it via ChatGpt, cuz I know no programing.
> 
> https://pastebin.com/5sxnc7xM

I'll take a look.

**Comment by Aang488** [comment]
> > Kindly have a look at it, I generated it via ChatGpt, cuz I know no programing.
> > https://pastebin.com/5sxnc7xM
> 
> I'll take a look.

Thanks for the support and kindness ❤️

**Comment by igorlogius** [comment]
@Aang488 

Damn, i didnt even want to spend time on this today, but you roped me into it ... so here is the result. As usual i took some liberal shortcuts, but overall it should be an improvement. 

https://user-images.githubusercontent.com/67047467/235377684-d3b940b7-6652-46f9-8adf-8251cfbda91f.mp4

**Comment by igorlogius** [comment]
PS: The Bubble Drag and Drop doenst work on Mobile ... yet ... i'll have to look into that at another time. i think for touch devices i might have to register a different event or something.

**Comment by Aang488** [comment]
> @Aang488 
> 
> Damn, i didnt even want to spend time on this today, but you roped me into it ... so here is the result. As usual i took some liberal shortcuts, but overall it should be an improvement. 
> 
> https://user-images.githubusercontent.com/67047467/235377684-d3b940b7-6652-46f9-8adf-8251cfbda91f.mp4
> 

This one looks great. Sorries for taking your time.

**Comment by Aang488** [comment]
Is there anyway to remove this last issue, am okay with it this way as well, but if resolved will be better, or could give me a quick trick to solve it myself. First of all, thanks for the support.
In Firefox Android, for some words the pop up's more button is hidden by the settings of Firefox Android, in the previous version when one clicked on the pop up, the firefox settings disappeared, now they don't go anywhere. Even when the pop up is moved up or down the settings continue to hide the more button.

![image](https://user-images.githubusercontent.com/79444969/235465697-08654e48-048f-4b6b-8bc5-a409122c5a0d.png)

**Comment by igorlogius** [comment]
@Aang488 

I'll see what i can do.

**Comment by igorlogius** [comment]
@Aang488 

What kind of device are you using? 

![snip_20230501-162513](https://user-images.githubusercontent.com/67047467/235466986-7d00b690-1c25-428e-ab8c-616626a99bc7.png)
![snip_20230501-162534](https://user-images.githubusercontent.com/67047467/235466987-bcd6c7d6-9333-4d11-b0f6-3d2639c5dd6f.png)



I want to see if i can simulate the issue with the built-in device changer.

**Comment by Aang488** [comment]
POCO device with Android 12, miui 13

**Comment by igorlogius** [comment]
Well, damn, i can't seem to simulate the selection bar ... maybe i am doing something wrong. 
So i can not really simulate and test when the issue is solved/fixed. 

currently i just have to assume that it has something todo with making the bubble draggable, since you said this was a new issue, and i dont quite know what else would be causing this.  

So i'll push out a new version, whichout the dragElement support and you tell me if that fixed the issue or not. Hope that sounds ok.

**Comment by Aang488** [comment]
I recorded a short video, where do I  upload it to show you?

**Comment by Aang488** [comment]
> Well, damn, i can't seem to simulate the selection bar ... maybe i am doing something wrong. So i can not really simulate and test when the issue is solved/fixed.
> 
> currently i just have to assume that it has something todo with making the bubble draggable, since you said this was a new issue, and i dont quite know what else would be causing this.
> 
> So i'll push out a new version, without the dragElement support and you tell me if that fixed the issue or not. Hope that sounds ok.

Issue Resolved. Perfect 💯
