### ISSUE TITLE
Option for sources other than Google

### ISSUE THREAD

**Issue by wesinator** [igorlogius/dbl-click-dict#6]
Hi, thanks for the work on this extension, especially for Fenix.

It would be great if the defn source was configurable, not just Google. https://github.com/igorlogius/dbl-click-dict/blob/25fa5f8fb0fdf143af6d2849fba9a66c31543b96/background.js#L26

[NO_TRAIN]::

**Comment by igorlogius** [comment]
Well, what  other sources do you have in mind?

**Comment by wesinator** [comment]
the author of the original dictionary anywhere extension has this foss service https://dictionaryapi.dev/ it seems

(they also still use google in their extension, interestingly).

**Comment by igorlogius** [comment]
I am marking this feature as out of scope for the moment, but i might reconsider at one point in the future ... we'll see.
