### ISSUE TITLE
[Android] Definition pane doesn't show on some websites

### ISSUE THREAD

**Issue by wesinator** [igorlogius/dbl-click-dict#7]
**Describe the bug**
Definition pane doesn't show on some websites, when on android 

**Steps to Reproduce**
1. open https://alephone.cebix.net/
1. Double tap a word in the "General information" section.

**Expected Result**
Definition pane shows up

**Actual Result**
Definition pane doesn't show up

**Additonal Information:**
-  Firefox for Android 123.1.0

**Comment by igorlogius** [comment]
i'll take a look and try to reproduce the issue

**Comment by igorlogius** [comment]
After switching to "Desktop-Mode" because tapping otherwise zoomes the page, i can double tap any word in the "general information" section on my android devices and the virtual android device in my browser and the definiton popup opens as expected.  

![Screenshot_2024-03-18_20-31-00](https://github.com/igorlogius/dbl-click-dict/assets/67047467/d12549a0-e432-4cce-a3c1-509df82be0ca)

**Comment by igorlogius** [comment]
Sidenote: i noticed, that enabeling Desktop-Mode on at least one of my devices doest nothing in regards to preventing double tapping from not zooming. This effectively prevents the usage of the addon ... not sure if this is an issue with firefox or the operation system ... it's kind of annoying.

**Comment by igorlogius** [comment]
I'll leave this Bug open for now, but without any addional infomration, i can't really do anything here. Sorry.

**Comment by wesinator** [comment]
what information do you need from me?
I agree the bug seems to be on pages that do a double-tap zoom on mobile. I also tested on w3schools pages and they seem to have a similar issue, I can't tell whether that's due to the zoom or something else (possibly certain css styles).

[NO_TRAIN]::

**Comment by igorlogius** [comment]
I made some changes ... which on my side seem to improve things.
Let me know if the new version fixes this issue for you or not.

**Comment by igorlogius** [comment]
https://github.com/igorlogius/dbl-click-dict/assets/67047467/ad61d99a-22e4-43c1-8694-4ae14a2b3813

**Comment by igorlogius** [comment]
Sadly there is nothing i know about which could be dont about the browser built-in selection menu from opening up too, but ... i hope it's not too much of bother. Clicking into the definition bubble easily closes the menu.

**Comment by wesinator** [comment]
This change means that a single tap on any text will automatically send the selection to Google on any site.
I think this is a problem for privacy and astonishing behaviour.
I actually prefer the 2.2.7 behaviour even if it doesn't work on a few websites.

Sorry for the inconvenience, I know you spent time on this. I think if there's a way you can have the prior behavior but allow zoom pages to also load the popup would be ideal.

[NO_TRAIN]::

**Comment by igorlogius** [comment]
> a single tap on any text will automatically send the selection to Google

technically it's not a single tab but a "press where you hold down for a second"

> I think this is a problem for privacy and astonishing behaviour.

ok, yeah when you accidentally select something "private" i guess you are right. 
on desktop one could just use one of the "trigger keys" or i could use the browserAction to disable the function or i could just use a context menu entry ... but on android ... this is all not doable. This is a bit frustrating. 

I dont really want to revert the function, without having some kind of solution for the inital problem ... which i still dont 100% how on some pages the behaviour triggers a zoom and in others it selcts text. 

I looked at the CSS but could not identify anything that seems to be responsible for this, so i am a bit stumped now.

**Comment by igorlogius** [comment]
I just got a maybe terrible idea ... 

i could after selecting selecting some text first show the bubble without doing a lookup but instead containing a confimration button, that the user would need to click on, before the actual lookup would be made. 

That would add one more click, but i since the user needs to dismiss the browser context menu anyway that might not be such a bad thing. 

What do you think?

**Comment by igorlogius** [comment]
Immediate fix to remdidate the privacy issue

https://github.com/igorlogius/dbl-click-dict/assets/67047467/5c484280-1b63-4bd8-8fce-e5030db517a9

**Comment by igorlogius** [comment]
Locking this issue for now, since the original problem was solved. 

Please open a new issue for further concerns/requests
