### ISSUE TITLE
Add option to disable the confirmation Prompt when a new word should be looked up

### ISSUE THREAD

**Issue by rehman-talha** [igorlogius/dbl-click-dict#8]
**Describe the bug**
Whenever a word is double clicked for the first time, this below popup opens which asks for permission.
Like this:

![image](https://github.com/igorlogius/dbl-click-dict/assets/93119114/f6da9b53-fcba-48d1-adfb-b573c23af167)

When given the permission, the definition loads after that.

**To Reproduce**
1. Install the latest firefox v.124.0.1.0
2. Install this addon
3. double click a word
4. See the unnecessary popup

**Expected behavior**
I expected the definition to load

**Screenshots**
![image](https://github.com/igorlogius/dbl-click-dict/assets/93119114/5a7bccba-a7ba-49b1-96cb-4ae6dd1e2643)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [Firefox]
 - Version [124.0.1.0]

**Additional context**

**Comment by wesinator** [comment]
https://github.com/igorlogius/dbl-click-dict/issues/7#issuecomment-2021183198

**Comment by igorlogius** [comment]
Sorry for the unprompted upate.  I just wanted to protect users from involentery sending   data to googles dictionary api, as @wesinator  pointed out to me and this was the quickest way to go  about it.  

But i guessi need to add an option to disable the confirmation dialog for people who dont care about this (aka. dont use their device for sensitive stuff)

**Comment by igorlogius** [comment]
Option added to `2.2.12`

**Comment by wesinator** [comment]
I think this still isn't the best user experience - on my device, the addon dialog opens _every_ time I tap text to select, no matter how long or short (i.e. how quickly) I hold the selection on the touchscreen.
Contrary to what you say in https://github.com/igorlogius/dbl-click-dict/issues/7#issuecomment-2021168199, on my device (Firefox 124.1.0 on Android 9), I have been unable to reproduce a case where the system/app selection dialog comes up but not the app. Maybe on your device it's possible to do a quick tap that prevents the app from loading the confirmation or the lookup, but that clearly is not the universal behaviour. (I have no known non-default settings that would affect this at the system level).

> But i guessi need to add an option to disable the confirmation dialog for people who dont care about this (aka. dont use their device for sensitive stuff)

For what it's worth, I don't want the extension making a request to Google every time I tap something regardless; it's unnecessary. As I stated above, we seem to have different user experiences as to whether the selection gets sent on _any_ tap selection of text.

[NO_TRAIN]::
