### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wesinator** [igorlogius/dbl-click-dict#9]
A BSD-2 license was introduced with 62da167

It seems that this addon is a fork of https://github.com/meetDeveloper/Dictionary-Anywhere, which has a GPL-3.0 license.
BSD licenses are a subset of the GPL, but I think this would also need to be GPL-3 and retain the original author copyright to be compliant.

[NO_TRAIN]::

**Comment by igorlogius** [comment]
noted ... i'll look into fixing that.
